name: CI/CD Pipeline

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run tests
        run: npm test -- --ci --watchAll=false

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      VITE_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      VITE_NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      VITE_STOCK_API_KEY: ${{ secrets.STOCK_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: dist

      - name: Install dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libwoff2-1 \
            libvpx15 \
            libevent-2.1-7 \
            libopus0 \
            gstreamer1.0-tools \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            libsecret-1-0 \
            libhyphen0 \
            libx264-163 \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libdrm2 \
            libgbm1 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libpango-1.0-0 \
            libharfbuzz0b

      - name: Run Playwright screenshot
        if: github.ref == 'refs/heads/main'
        run: |
          npm ci
          npx playwright install
          npx playwright test tests/screenshot.spec.js \
            --web-server-command "npm run preview" \
            --web-server-url "http://localhost:4173" \
            --web-server-timeout 60s

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-build
          path: dist
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./dist
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
